### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by Anulo2** [mhkafadar/notifine#1]
Hey there, this project looks great, i've been looking for a gitlab_bot (Integram) alternative for a long time and I've finally found this. It would be great to have also an example of docker compose to setup everything withous using aws, I'm working on a possibile docker compose on my own and if it works well enough  I will try and publish it somewhere but it would be great to have an official example. Thanks for all the great work!

**Comment by Anulo2** [comment]
I had to add some code to do the db migrations like this to make everything work:

![image](https://user-images.githubusercontent.com/28984474/219393696-323bd992-3bb0-4adb-a5f1-3eede66ffbbc.png)

the docker compose i've come up with looks something like this:

```yaml
version: '3'

services:
  notifine-bot:
    container_name: '${COMPOSE_PROJECT_NAME}-notifine-bot'
    build: .
    restart: unless-stopped
    networks:
      - telegram_bots
    environment:
      - GITLAB_TELOXIDE_TOKEN=${GITLAB_TELOXIDE_TOKEN}
      - DATABASE_URL=postgresql://notifine:${DATABASE_PASSWORD}@notifine-db
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - RUST_BACKTRACE=1
      - TELEGRAM_ADMIN_CHAT_ID=${TELEGRAM_ADMIN_CHAT_ID}

    depends_on:
      - notifine-db
    expose:
      - 8080

  notifine-db:
    container_name: '${COMPOSE_PROJECT_NAME}-notifine-db'
    image: postgres:11
    restart: unless-stopped
    networks:
      - telegram_bots
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=notifine
      - PUID=1000
      - GUID1000
    expose:
      - 5432

networks:
  telegram_bots:
    name: telegram_bots
```


if you want I cand do a pr :D
